name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: cowsay:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build image
        run: docker build -t cowsay .
        
      - name: Start Container
        run: docker run -d --rm --name=cowsay -p 127.0.0.1:8080 cowsay

      - name: sleep
        run: sleep 10

      - name: Test Container
        run: curl -v http://localhost:8080

  # push:
  #   runs-on: ubuntu-latest
  #   needs: test

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - name: Build Docker Image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: ./Dockerfile
  #         push: true
  #         tags: takleasmalesh/cowsay:tagname
  #       env:
  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
