name: Cowsay CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Cowsay
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
